name: Android CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Release APK
        run: ./gradlew clean assembleRelease

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone

          cat > ~/.config/rclone/rclone.conf <<EOF
          [gdrive]
          type = drive
          scope = drive
          service_account_credentials = ${GDRIVE_SERVICE_ACCOUNT_JSON}
          EOF
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}

      - name: Get next build number
        id: buildnum
        run: |
          COUNT=$(rclone lsf gdrive:${{ secrets.GDRIVE_FOLDER_ID }} --files-only | wc -l)
          NEXT=$((COUNT + 1))
          echo "build=$NEXT" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          APK=$(find Reef/build/outputs/apk/release -name "*.apk" | head -n 1)

          cp "$APK" "Reef-v${{ steps.buildnum.outputs.build }}.apk"

      - name: Upload APK to Google Drive
        run: |
          rclone copy "Reef-v${{ steps.buildnum.outputs.build }}.apk" \
          gdrive:${{ secrets.GDRIVE_FOLDER_ID }} \
          --progress